### ISSUE TITLE
raise `AttributeError` at open jxl file

### ISSUE THREAD

**Issue by wyn1995** [Isotr0py/pillow-jpegxl-plugin#11]
since pillow 10.1.0, `PIL.Image.Image.mode` is a [property](https://github.com/python-pillow/Pillow/blob/10.1.0/src/PIL/Image.py#L508) ([changelog](https://pillow.readthedocs.io/en/stable/releasenotes/10.1.0.html#setting-image-mode)), so use `pillow` >= 10.1.0 can receive an `AttributeError` when open jxl file:
```python
import pillow_jxl
from PIL import Image


def main() -> None:
    image = Image.open("./test.jxl")
    try:
        # do something...
        pass
    finally:
        image.close()


if __name__ == "__main__":
    main()

```

```
Traceback (most recent call last):
  ...
  File "test.py", line 15, in <module>
    main()
  File "test.py", line 6, in main
    image = Image.open("./test.jxl")
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/Lib/site-packages/PIL/Image.py", line 3288, in open
    im = _open_core(fp, filename, prefix, formats)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/Lib/site-packages/PIL/Image.py", line 3274, in _open_core
    im = factory(fp, filename)
         ^^^^^^^^^^^^^^^^^^^^^
  File "venv/Lib/site-packages/PIL/ImageFile.py", line 137, in __init__
    self._open()
  File "venv/Lib/site-packages/pillow_jxl/JpegXLImagePlugin.py", line 30, in _open
    self.mode = self.rawmode = self._jxlinfo.mode
    ^^^^^^^^^
AttributeError: property 'mode' of 'JXLImageFile' object has no setter
```

**Comment by abionics** [comment]
The same issue

**Comment by Isotr0py** [comment]
Thanks for reporting the issue!

I have updated a new version to fix it. It should work with `pillow>=10.1.0` (tested with `pillow==10.2.0`)
